### ISSUE TITLE
Sometimes it shows this error when using with `fzf-lua`.

### ISSUE THREAD

**Issue by nyngwang** [numToStr/FTerm.nvim#44] opened 2021-11-09 12:58 UTC
```
E5108: Error executing lua ...site/pack/packer/start/FTerm.nvim/lua/FTerm/terminal.lua:97: Window was closed immediately
stack traceback:
        [C]: in function 'nvim_open_win'
        ...site/pack/packer/start/FTerm.nvim/lua/FTerm/terminal.lua:97: in function 'create_win'
        ...site/pack/packer/start/FTerm.nvim/lua/FTerm/terminal.lua:163: in function 'open'
        ...site/pack/packer/start/FTerm.nvim/lua/FTerm/terminal.lua:208: in function 'toggle'
        ...are/nvim/site/pack/packer/start/FTerm.nvim/lua/FTerm.lua:37: in function 'toggle'
        [string ":lua"]:1: in main chunk
```

I encountered this error when using `fzf-lua`'s `git_status` function. I pressed `<ESC>` after I finished reading the `git diff` of files.

**Comment by numToStr** [comment] 2021-11-09 13:15
This is bizarre 😄. Can you paste your config for `FTerm` and `fzf-lua`?

**Comment by nyngwang** [comment] 2021-11-09 13:46
## FTerm

```
use {
  'numtostr/FTerm.nvim',
  config = function()
    require'FTerm'.setup {
      border = 'single',
      hl = 'Normal',
      blend = 25, -- transparency
      dimensions = {
        height = 0.6,
        width = 1,
        x = 0,
        y = 1,
      }
    }
  end,
}
vim.api.nvim_set_keymap('n', '<M-Tab>', '<cmd>lua require("FTerm").toggle()<CR>', NOREF_NOERR_TRUNC)
vim.api.nvim_set_keymap('t', '<M-Tab>', '<cmd>lua require("FTerm").toggle()<CR>', NOREF_NOERR_TRUNC)
```

## fzf-lua

```
use {
  'ibhagwan/fzf-lua',
  requires = {
    -- WARNING: nvim-fzf is not fzf itself, install it using brew!
    'vijaymarupudi/nvim-fzf',
    'kyazdani42/nvim-web-devicons'
  },
  config = function()
    require'fzf-lua'.setup {
      winopts = {
        border =  { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
        height = 0.65,
        width = 0.7,
        row = 0.9,
        col = 200,
        preview = {
          default = 'bat',
          title = false,
          wrap = 'nowrap',
          vertical = 'up:80%',
          layout = 'vertical'
        }
      },
      files = {
        prompt = ' File $ ',
        -- WARNING: Run `brew install bat` to install bat.
        cmd = 'fd -H',
      },
      grep = {
        prompt = ' Word $ ',
        -- WARNING: Run `brew install ripgrep` to install ripgrep.
        cmd = "rg --vimgrep -g '!{.git,node_modules,package-lock.json,yarn.lock,Library,tags}'",
        color_icons = false,
        file_icons = false,
      },
      previewers = {
        cat = {
          cmd = "cat",
          args = ""
        }
      }
    }
    local nnoremap = vim.keymap.nnoremap
    nnoremap { '<Leader>gs', function() require'fzf-lua'.git_status() end }
    nnoremap { '<Leader>gl', function() require'fzf-lua'.git_commits() end }
    nnoremap { '<Leader>gb', function() require'fzf-lua'.git_branches() end }
    nnoremap { '<Leader>gp', function() require'fzf-lua'.git_files() end }
    ------------------------------------------------------------------------------------------------
    nnoremap { '<Leader>h', function() require'fzf-lua'.command_history() end }
    nnoremap { '<Leader>c', function() require'fzf-lua'.colorschemes() end }
    ------------------------------------------------------------------------------------------------
    nnoremap { '<C-F>', function() require'fzf-lua'.live_grep() end }
    nnoremap { '<C-G>', function() require'fzf-lua'.files() end }
  end
}
```

**Comment by numToStr** [comment] 2021-11-13 07:43
I tried and I couldn't reproduce the error. Would you mind telling me the exact steps?

**Comment by numToStr** [comment] 2021-12-11 10:40
I am closing this as I don't think this is related to this plugin.

**Closed by numToStr** 2021-12-11 10:40 UTC
